apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 80
    - name: https
      protocol: TCP
      targetPort: 443
      port: 443
  type: LoadBalancer
  
      
